### ISSUE TITLE
has to be type "number" but received type "string"

### ISSUE THREAD

**Issue by crunchip77** [iobroker-community-adapters/ioBroker.smartcontrol#16]
Es handelt sich um diese Warnmeldungen, **duration** und **briThreshold** has to be type "number" but received type "string"

`<html>
<body>

smartcontrol.0 | 2022-10-14 17:52:54.258 | info | State value to set for "smartcontrol.0.options.TriggerMotion.BWM Esstisch.briThreshold" has to be type "number" but received type "string"
-- | -- | -- | --
smartcontrol.0 | 2022-10-14 17:52:54.204 | info | State value to set for "smartcontrol.0.options.TriggerMotion.BWM Esstisch.duration" has to be type "number" but received type "string"

</body>
</html>`

**Comment by oelison** [comment]
Data conversion adapted with release v1.3.1.
