### ISSUE TITLE
Update stable version in repo from 1.3.2 to 2.0.1

### ISSUE THREAD

**Issue by GermanBluefox** [iobroker-community-adapters/ioBroker.smartcontrol#79]
# Think about update stable version to 2.0.1
**Version**: stable=**1.3.2** (301 days old) => latest=**2.0.1** (15 days old)
**Installs**: stable=**1382** (62.88%), latest=**214** (9.74%), total=**2198**

Click to use [developer portal](https://www.iobroker.dev/adapter/smartcontrol/releases)
Click to [edit](https://github.com/ioBroker/ioBroker.repositories/edit/master/sources-dist-stable.json#L2236)

Note: This is an automatically generated message and not personally authored by bluefox!

**Comment by mcm1957** [comment]
@oelison 
Do you know any reason to delay stable update any longer?

**Comment by GermanBluefox** [comment]
This issue seems to be outdated.

This issue suggests to update the stable version of this adapter to 2.0.1 but the current stable version is already 2.0.1.

So this issue should be closed.
